// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecocivicom_blazor_clone.Data;

#nullable disable

namespace ecocivicom_blazor_clone.Migrations
{
    [DbContext(typeof(FormationsCategoriesDataContext))]
    partial class FormationsCategoriesDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ecocivicom_blazor_clone.Data.FormationsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormationsCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "COCIVICOM vous accompagne dans votre démarche, en proposant des (formations éco-conduite pour entreprise)[https://www.ecocivicom.com/Formation_eco-conduite.b.htm]. Nous façonnons un programme adapté pour vos salariés, afin de les sensibiliser aux bonnes pratiques de l’éco-conduite.",
                            Image = "images/formations_categories/form_eco.webp",
                            Slug = "eco-conduite"
                        },
                        new
                        {
                            Id = 2,
                            Description = "En formant vos salariés au risque routier, vous pourrez diminuer le taux d'accidentologie de votre entreprise et réduirez également les coûts financiers et humains liés aux accidents de la route.",
                            Image = "images/formations_categories/form_rr.webp",
                            Slug = "risque-routier"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ECOCIVICOM, a acquis au fur-à-mesure des années de l'expérience dans différents domaines en lien avec la formation des salariés sur les thèmes de la sécurité des Biens et des Personnes.",
                            Image = "images/formations_categories/form_secu.webp",
                            Slug = "securite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "<u>Nouveau ! :</u> Nous proposons une partie de nos formations en classe virtuelle. Ces formations à distance via visioconférence nous permettent d'échanger et de faire des démonstrations pratiques avec nos stagiaires.",
                            Image = "images/formations_categories/form_cv.webp",
                            Slug = "classe-virtuelle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Image = "images/formations_categories/form_cv.webp",
                            Slug = "classe-virtuelle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
